version: "3"

services:
  pretalx:
    image: ghcr.io/thepatrick/pretalx-docker:0168987
    container_name: pretalx
    restart: unless-stopped
    depends_on:
      - redis
      - db
    volumes:
      - /opt/p2-network/campjs-cfp/cfg/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - /opt/p2-network/campjs-cfp/pretalx-data/:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.campjs-cfp-pretalx.rule=Host(`cfp.campjs.org`)"
      - "traefik.http.routers.campjs-cfp-pretalx.entrypoints=websecure"
      - "traefik.http.routers.campjs-cfp-pretalx.tls=true"
      - "traefik.http.routers.campjs-cfp-pretalx.tls.certresolver=campjs"
      - "traefik.http.routers.campjs-cfp-pretalx.tls.domains[0].main=cfp.campjs.org" 
      - "traefik.http.routers.campjs-cfp-redir.entrypoints=web"
      - "traefik.http.routers.campjs-cfp-redir.rule=Host(`cfp.campjs.org`)"
      - "traefik.http.routers.campjs-cfp-redir.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
    networks:
      default:
      traefik:

  db:
    image: mysql:latest
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - "/opt/p2-network/pretalx-db/:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: pretalx
      MYSQL_USER: pretalx
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_PASSWORD_FILE: /run/secrets/mysql_user_password
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    secrets:
      - mysql_user_password
      - mysql_root_password

  redis:
    image: redis:7.0.12-bookworm
    container_name: pretalx-redis
    restart: unless-stopped
    volumes:
      - "/opt/p2-network/pretalx-redis/:/data"

networks:
  traefik:
    name: traefik_default
    external: true

secrets:
  mysql_root_password:
    file: /opt/p2-network/run/DOCKER_CFP_MYSQL_ROOT_PASSWORD
  mysql_user_password:
    file: /opt/p2-network/run/DOCKER_CFP_MYSQL_USER_PASSWORD
