version: "3"

services:
  cfp:
    image: traefik/whoami:v1.10.1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.campjs-cfp-echo.rule=Host(`cfp.campjs.org`)"
      - "traefik.http.routers.campjs-cfp-echo.entrypoints=websecure"
      - "traefik.http.routers.campjs-cfp-echo.tls=true"
      - "traefik.http.routers.campjs-cfp-echo.tls.certresolver=campjs"
      - "traefik.http.routers.campjs-cfp-echo.tls.domains[0].main=cfp.campjs.org"

    networks:
      default:
      traefik:

  redis:
    image: redis:7.0.12-bookworm
    container_name: pretalx-redis
    restart: unless-stopped
    volumes:
      - "/opt/p2-network/pretalx-redis/:/data"


networks:
  traefik:
    name: traefik_default
    external: true
